version: '3'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: ddns.raghav1618.tech
    restart: unless-stopped
    environment:
      - API_KEY=-----------------
      - ZONE=raghav1618.tech
      - PROXIED=true
      - PUID=1000
      - GUID=1000
    networks:
      - proxy     

networks:
  proxy:
    external: true